DROP TABLE IF EXISTS todo;

CREATE TABLE IF NOT EXISTS todo (
  id SERIAL PRIMARY KEY,
  task TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_done BOOLEAN NOT NULL DEFAULT FALSE,
  done_at TIMESTAMPTZ
)